POPULANDO TABELAS

TABELA PRECO

INSERT INTO PRECO (COR, VALOR) VALUES ('CO', 5.00);
INSERT INTO PRECO (COR, VALOR) VALUES ('PB', 3.50);
INSERT INTO PRECO (COR, VALOR) VALUES ('3D', 8.00);

TABELA GENERO

INSERT INTO GENERO VALUES (1, 'AÇÃO');
INSERT INTO GENERO VALUES (2, 'COMÉDIA');
INSERT INTO GENERO VALUES (3, 'DRAMA');
INSERT INTO GENERO VALUES (4, 'TERROR');
INSERT INTO GENERO VALUES (5, 'ANIMAÇÃO');
INSERT INTO GENERO VALUES (6, 'ROMANCE');
INSERT INTO GENERO VALUES (7, 'FICÇÃO');
INSERT INTO GENERO VALUES (8, 'DOCUMENTÁRIO');


TABELA CLIENTE

INSERT INTO CLIENTE (CODCLIENTE, NOMCLIENTE, ENDCLIENTE, BAIRCLIENTE, CIDCLIENTE, UFCLIENTE) VALUES (1,'Maria Silva', 'Rua das Flores, 10','Centro', 'São Paulo', 'SP')

INSERT INTO CLIENTE (CODCLIENTE, NOMCLIENTE, ENDCLIENTE, BAIRCLIENTE, CIDCLIENTE, UFCLIENTE) VALUES (2,'João Souza', 'Av Brasil, 200','Copacabana', 'Rio de Janeiro', 'RJ')

INSERT INTO CLIENTE (CODCLIENTE, NOMCLIENTE, ENDCLIENTE, BAIRCLIENTE, CIDCLIENTE, UFCLIENTE) VALUES (3,'Ana Costa', 'Rua A, 45','Savassi', 'Belo Horizonte', 'MG')

INSERT INTO CLIENTE (CODCLIENTE, NOMCLIENTE, ENDCLIENTE, BAIRCLIENTE, CIDCLIENTE, UFCLIENTE) VALUES (4,'Carlos Lima', 'Rua B, 78','Asa Sul', 'Brasília', 'DF')


INSERT INTO CLIENTE (CODCLIENTE, NOMCLIENTE, ENDCLIENTE, BAIRCLIENTE, CIDCLIENTE, UFCLIENTE) VALUES (5,'Fernanda Rocha', 'Rua C, 120','Centro', 'Curitiba', 'PR')

TABELA FILME

INSERT INTO FILME VALUES (1, 'Velozes & Furiosos', 'CO','D',1);
INSERT INTO FILME VALUES (2, 'Toy Story', 'CO','D',5);
INSERT INTO FILME VALUES (3, 'O Exorcista', 'PB','L',4);
INSERT INTO FILME VALUES (4, 'Titanic', 'PB','D',3);
INSERT INTO FILME VALUES (5, 'As Branquelas', 'CO','D',2);
INSERT INTO FILME VALUES (6,'Interestelar','CO','D',7);
INSERT INTO FILME VALUES (7,'Invocação do Mal','CO','D',4);
INSERT INTO FILME VALUES (8,'Procurando Nemo','CO','D',5);
INSERT INTO FILME VALUES (9,'Clube da Luta','PB','D',3);
INSERT INTO FILME VALUES (10,'Homem-Aranha','3D','D',1);
INSERT INTO FILME VALUES (11,'Se Beber Não Case','CO','D',2);
INSERT INTO FILME VALUES (12,'Diário de uma Paixão','CO','D',6);
INSERT INTO FILME VALUES (13,'Matrix','CO','D',7);
INSERT INTO FILME VALUES (14,'Corra!','CO','D',4);
INSERT INTO FILME VALUES (15,'Up - Altas Aventuras','CO','D',5);



TABELA LOCACAO

INSERT INTO LOCACAO (CODCLIENTE, DATALOC, CODFILME, DATADEVOLUCAO) VALUES (1, (TO_DATE('10/02/2026','DD/MM/YYYY')),3, (TO_DATE('15/02/2026','DD/MM/YYYY')))

INSERT INTO LOCACAO (CODCLIENTE, DATALOC, CODFILME, DATADEVOLUCAO) VALUES (2, (TO_DATE('12/02/2026','DD/MM/YYYY')),1,NULL)

INSERT INTO LOCACAO (CODCLIENTE, DATALOC, CODFILME, DATADEVOLUCAO) VALUES (3, (TO_DATE('14/02/2026','DD/MM/YYYY')),2, (TO_DATE('18/02/2026','DD/MM/YYYY')))