-- 1. Listar todos os filmes com descrição do gênero

SELECT F.NOMEFILME, G.DESCRICAO
FROM FILME F JOIN GENERO G ON F.CODGENERO = G.CODGENERO;

-- 2. Listar locações com nome do cliente e nome do filme

SELECT C.NOMCLIENTE, F.NOMEFILME
FROM CLIENTE C JOIN LOCACAO L ON C.CODCLIENTE = L.CODCLIENTE 
JOIN FILME F ON L.CODFILME = F.CODFILME;

-- 3. Filmes que estão locados

SELECT NOMEFILME
FROM FILME
WHERE STATUS = 'L';

-- 4. Clientes que nunca alugaram

SELECT NOMCLIENTE
FROM CLIENTE C LEFT JOIN LOCACAO L ON C.CODCLIENTE = L.CODCLIENTE
WHERE L.CODCLIENTE IS NULL;

-- 5. Quantidade de filmes alugados por nome do cliente

SELECT C.NOMCLIENTE, COUNT (L.CODLOCACAO) as QTD_FILMES_ALUGADOS
FROM CLIENTE C LEFT JOIN LOCACAO L ON C.CODCLIENTE = L.CODCLIENTE
GROUP BY C.NOMCLIENTE;

-- 6.Total gasto com locações por cliente

SELECT C.NOMCLIENTE, SUM (P.VALOR) as TOTAL_GASTO
FROM CLIENTE C LEFT JOIN LOCACAO L ON C.CODCLIENTE = L.CODCLIENTE
LEFT JOIN FILME F ON L.CODFILME = F.CODFILME 
LEFT JOIN PRECO P ON F.COR = P.COR
GROUP BY C.NOMCLIENTE;

-- 7. Filme mais alugado

SELECT F.NOMEFILME, COUNT (L.CODLOCACAO) as QTD_VEZES_ALUGADO
FROM FILME F JOIN LOCACAO L ON F.CODFILME = L.CODFILME
GROUP BY F.NOMEFILME 
ORDER BY QTD_VEZES_ALUGADO DESC
FETCH FIRST 1 ROW ONLY;

-- 8. Clientes que gastaram mais que 10 reais

SELECT C.NOMCLIENTE, SUM (P.VALOR) as TOTAL_GASTO
FROM CLIENTE C LEFT JOIN LOCACAO L ON C.CODCLIENTE = L.CODCLIENTE
LEFT JOIN FILME F ON L.CODFILME = F.CODFILME 
LEFT JOIN PRECO P ON F.COR = P.COR
GROUP BY C.NOMCLIENTE
HAVING SUM (P.VALOR) > 10

-- 9. Clientes que gastaram acima da média

SELECT C.NOMCLIENTE, SUM (P.VALOR) as TOTAL_GASTO
FROM CLIENTE C LEFT JOIN LOCACAO L ON C.CODCLIENTE = L.CODCLIENTE
LEFT JOIN FILME F ON L.CODFILME = F.CODFILME 
LEFT JOIN PRECO P ON F.COR = P.COR
GROUP BY C.NOMCLIENTE
HAVING SUM (P.VALOR) > (SELECT AVG (TOTAL_GASTO)
                        FROM(
                            SELECT SUM(P2.VALOR) AS TOTAL_GASTO
                            FROM CLIENTE C2 
                            LEFT JOIN LOCACAO L2 ON C2.CODCLIENTE = L2.CODCLIENTE
                            LEFT JOIN FILME F2 ON L2.CODFILME = F2.CODFILME 
                            LEFT JOIN PRECO P2 ON F2.COR = P2.COR
                            GROUP BY C2.CODCLIENTE
                        )
);

-- 10. View com clientes acima da média

CREATE VIEW CLIENTES_ACIMA_DA_MEDIA AS
SELECT C.NOMCLIENTE, SUM (P.VALOR) as TOTAL_GASTO
FROM CLIENTE C LEFT JOIN LOCACAO L ON C.CODCLIENTE = L.CODCLIENTE
LEFT JOIN FILME F ON L.CODFILME = F.CODFILME 
LEFT JOIN PRECO P ON F.COR = P.COR
GROUP BY C.NOMCLIENTE
HAVING SUM (P.VALOR) > (SELECT AVG (TOTAL_GASTO)
                        FROM(
                            SELECT SUM(P2.VALOR) AS TOTAL_GASTO
                            FROM CLIENTE C2 
                            LEFT JOIN LOCACAO L2 ON C2.CODCLIENTE = L2.CODCLIENTE
                            LEFT JOIN FILME F2 ON L2.CODFILME = F2.CODFILME 
                            LEFT JOIN PRECO P2 ON F2.COR = P2.COR
                            GROUP BY C2.CODCLIENTE
                        )
);

-- 11. Atualizar STATUS do filme automaticamente quando inserir a locação

-- Quando inserir locação >>> Filme fica 'Locado'

CREATE OR REPLACE TRIGGER TRG_LOCACAO_FILME
AFTER INSERT ON LOCACAO
FOR EACH ROW
BEGIN
    UPDATE FILME
    SET STATUS = 'L'
    WHERE CODFILME = :NEW.CODFILME;
END;
/

-- Quando devolver filme >>> Sttaus volta para 'Disponível'

CREATE OR REPLACE TRIGGER TRG_DEVOLUCAO_FILME
AFTER UPDATE OF DATADEVOLUCAO ON LOCACAO
FOR EACH ROW
WHEN (NEW.DATADEVOLUCAO IS NOT NULL)
BEGIN
    UPDATE FILME
    SET STATUS = 'D'
    WHERE CODFILME = :NEW.CODFILME;
END;
/

