-- 1. Listar todos os filmes com descrição do gênero

SELECT F.NOMEFILME, G.DESCRICAO
FROM FILME F JOIN GENERO G ON F.CODGENERO = G.CODGENERO;

-- 2. Listar locações com nome do cliente e nome do filme

SELECT C.NOMCLIENTE, F.NOMEFILME
FROM CLIENTE C JOIN LOCACAO L ON C.CODCLIENTE = L.CODCLIENTE 
JOIN FILME F ON L.CODFILME = F.CODFILME;

-- 3. Filmes que estão locados

SELECT NOMEFILME
FROM FILME
WHERE STATUS = 'L';

-- 4. Clientes que nunca alugaram

SELECT NOMCLIENTE
FROM CLIENTE C LEFT JOIN LOCACAO L ON C.CODCLIENTE = L.CODCLIENTE
WHERE L.CODCLIENTE IS NULL;

-- 5. Quantidade de filmes alugados por nome do cliente

SELECT C.NOMCLIENTE, COUNT (L.CODLOCACAO) as QTD_FILMES_ALUGADOS
FROM CLIENTE C LEFT JOIN LOCACAO L ON C.CODCLIENTE = L.CODCLIENTE
GROUP BY C.NOMCLIENTE;

-- 6.Total gasto com locações por cliente

SELECT C.NOMCLIENTE, SUM (P.VALOR) as TOTAL_GASTO
FROM CLIENTE C LEFT JOIN LOCACAO L ON C.CODCLIENTE = L.CODCLIENTE
LEFT JOIN FILME F ON L.CODFILME = F.CODFILME 
LEFT JOIN PRECO P ON F.COR = P.COR
GROUP BY C.NOMCLIENTE;

-- 7. Filme mais alugado

SELECT F.NOMEFILME, COUNT (L.CODLOCACAO) as QTD_VEZES_ALUGADO
FROM FILME F JOIN LOCACAO L ON F.CODFILME = L.CODFILME
GROUP BY F.NOMEFILME 
ORDER BY QTD_VEZES_ALUGADO DESC
FETCH FIRST 1 ROW ONLY;