-- 1. Listar todos os filmes com descrição do gênero

SELECT F.NOMEFILME, G.DESCRICAO
FROM FILME F JOIN GENERO G ON F.CODGENERO = G.CODGENERO

-- 2. Listar locações com nome do cliente e nome do filme

SELECT C.NOMCLIENTE, F.NOMEFILME
FROM CLIENTE C JOIN LOCACAO L ON C.CODCLIENTE = L.CODCLIENTE 
JOIN FILME F ON L.CODFILME = F.CODFILME

-- 3. Filmes que estão locados

SELECT NOMEFILME
FROM FILME
WHERE STATUS = 'L'

-- 4. Clientes que nunca alugaram

SELECT NOMCLIENTE
FROM CLIENTE C LEFT JOIN LOCACAO L ON C.CODCLIENTE = L.CODCLIENTE
WHERE L.CODCLIENTE IS NULL